name: example
description: Showcase Arna Web Service.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  arna_web_service:
    path: ../
  arna:
    git: https://github.com/MahanRahmati/Arna.git
  arna_logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
