name: arna_web_service
description: Arna Web Service is a simple and powerful HTTP package for Flutter.
homepage: https://github.com/MahanRahmati/arna_web_service
version: 2.4.0
topics:
  - network
  - http
  - rest
  - client

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  arna_logger: ^1.1.0
  connectivity_plus: ^5.0.1
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
