name: arna_web_service
description: Arna Web Service is a simple and powerful HTTP package for Flutter.
homepage: https://github.com/MahanRahmati/arna_web_service
version: 1.2.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  arna_logger: ^1.0.7
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
